<?php
/**
* This class is autogenerated by the Spapi class generator
* Date of generation: 2022-05-26
* Specification: https://github.com/amzn/selling-partner-api-models/blob/main/models/authorization-api-model/authorization.json
* Source MD5 signature: 44dd520cbab054b2a1868d55e70ac413
*
*
* Selling Partner API for Authorization
* The Selling Partner API for Authorization helps developers manage authorizations and check the specific permissions associated with a given authorization.
*/
namespace DoubleBreak\Spapi\Api;
use DoubleBreak\Spapi\Client;

class Authorization extends Client {

  /**
  * Operation getAuthorizationCode
  *
  * @param array $queryParams
  *    - *sellingPartnerId* string - The seller ID of the seller for whom you are requesting Selling Partner API authorization. This must be the seller ID of the seller who authorized your application on the Marketplace Appstore.
  *    - *developerId* string - Your developer ID. This must be one of the developer ID values that you provided when you registered your application in Developer Central.
  *    - *mwsAuthToken* string - The MWS Auth Token that was generated when the seller authorized your application on the Marketplace Appstore.
  *
  */
  public function getAuthorizationCode($queryParams = [])
  {
    return $this->send("/authorization/v1/authorizationCode", [
      'method' => 'GET',
      'query' => $queryParams,
    ]);
  }

  public function getAuthorizationCodeAsync($queryParams = [])
  {
    return $this->sendAsync("/authorization/v1/authorizationCode", [
      'method' => 'GET',
      'query' => $queryParams,
    ]);
  }
}
