<?php
/**
* This class is autogenerated by the Spapi class generator
* Date of generation: 2020-12-06
* Specification: https://raw.githubusercontent.com/amzn/selling-partner-api-models/main/models/catalog-items-api-model/catalogItemsV0.json
* Source MD5 signature: 392e6cd67a086ae04070ee409a55b353
*/
namespace DoubleBreak\Spapi\Api;
use DoubleBreak\Spapi\Client;

class CatalogItems extends Client {

  /**
  * Operation listCatalogItems
  *
  * @param array $queryParams
  *    - *MarketplaceId* string - A marketplace identifier. Specifies the marketplace for which items are returned.
  *    - *Query* string - Keyword(s) to use to search for items in the catalog. Example: 'harry potter books'.
  *    - *QueryContextId* string - An identifier for the context within which the given search will be performed. A marketplace might provide mechanisms for constraining a search to a subset of potential items. For example, the retail marketplace allows queries to be constrained to a specific category. The QueryContextId parameter specifies such a subset. If it is omitted, the search will be performed using the default context for the marketplace, which will typically contain the largest set of items.
  *    - *SellerSKU* string - Used to identify an item in the given marketplace. SellerSKU is qualified by the seller's SellerId, which is included with every operation that you submit.
  *    - *UPC* string - A 12-digit bar code used for retail packaging.
  *    - *EAN* string - A European article number that uniquely identifies the catalog item, manufacturer, and its attributes.
  *    - *ISBN* string - The unique commercial book identifier used to identify books internationally.
  *    - *JAN* string - A Japanese article number that uniquely identifies the product, manufacturer, and its attributes.
  *
  */
  public function listCatalogItems($queryParams = [])
  {
    return $this->send("/catalog/v0/items", [
      'method' => 'GET',
      'query' => $queryParams,
    ]);
  }

  /**
  * Operation getCatalogItem
  *
  * @param string asin The Amazon Standard Identification Number (ASIN) of the item.
  *
  * @param array $queryParams
  *    - *MarketplaceId* string - A marketplace identifier. Specifies the marketplace for the item.
  *
  */
  public function getCatalogItem($asin, $queryParams = [])
  {
    return $this->send("/catalog/v0/items/{$asin}", [
      'method' => 'GET',
      'query' => $queryParams,
    ]);
  }

  /**
  * Operation listCatalogCategories
  *
  * @param array $queryParams
  *    - *MarketplaceId* string - A marketplace identifier. Specifies the marketplace for the item.
  *    - *ASIN* string - The Amazon Standard Identification Number (ASIN) of the item.
  *    - *SellerSKU* string - Used to identify items in the given marketplace. SellerSKU is qualified by the seller's SellerId, which is included with every operation that you submit.
  *
  */
  public function listCatalogCategories($queryParams = [])
  {
    return $this->send("/catalog/v0/categories", [
      'method' => 'GET',
      'query' => $queryParams,
    ]);
  }
}
