<?php
/**
* This class is autogenerated by the Spapi class generator
* Date of generation: 2021-07-03
* Specification: ttps://github.com/amzn/selling-partner-api-models/blob/main/models/catalog-items-api-model/catalogItems_2020-12-01.json
* Source MD5 signature: d4616aec873d2573c8c6237ffc03f766
*
*
* Selling Partner API for Catalog Items
* The Selling Partner API for Catalog Items provides programmatic access to information about items in the Amazon catalog.
*/
namespace DoubleBreak\Spapi\Api;
use DoubleBreak\Spapi\Client;

class CatalogItems extends Client {

  /**
  * Operation searchCatalogItems
  *
  * @param array $queryParams
  *    - *keywords* array - A comma-delimited list of words or item identifiers to search the Amazon catalog for.
  *    - *marketplaceIds* array - A comma-delimited list of Amazon marketplace identifiers for the request.
  *    - *includedData* array - A comma-delimited list of data sets to include in the response. Default: summaries.
  *    - *brandNames* array - A comma-delimited list of brand names to limit the search to.
  *    - *classificationIds* array - A comma-delimited list of classification identifiers to limit the search to.
  *    - *pageSize* integer - Number of results to be returned per page.
  *    - *pageToken* string - A token to fetch a certain page when there are multiple pages worth of results.
  *    - *keywordsLocale* string - The language the keywords are provided in. Defaults to the primary locale of the marketplace.
  *    - *locale* string - Locale for retrieving localized summaries. Defaults to the primary locale of the marketplace.
  *
  */
  public function searchCatalogItems($queryParams = [])
  {
    return $this->send("/catalog/2020-12-01/items", [
      'method' => 'GET',
      'query' => $queryParams,
    ]);
  }

  /**
  * Operation getCatalogItem
  *
  * @param string $asin The Amazon Standard Identification Number (ASIN) of the item.
  *
  * @param array $queryParams
  *    - *marketplaceIds* array - A comma-delimited list of Amazon marketplace identifiers. Data sets in the response contain data only for the specified marketplaces.
  *    - *includedData* array - A comma-delimited list of data sets to include in the response. Default: summaries.
  *    - *locale* string - Locale for retrieving localized summaries. Defaults to the primary locale of the marketplace.
  *
  */
  public function getCatalogItem($asin, $queryParams = [])
  {
    return $this->send("/catalog/2020-12-01/items/{$asin}", [
      'method' => 'GET',
      'query' => $queryParams,
    ]);
  }
}
