<?php
/**
* This class is autogenerated by the Spapi class generator
* Date of generation: 2022-01-09
* Specification: https://github.com/amzn/selling-partner-api-models/blob/main/models/fba-inventory-api-model/fbaInventory.json
* Source MD5 signature: 6de8a52a9cb4a2733ef714d85b4893f3
*
*
* Selling Partner API for FBA Inventory
* The Selling Partner API for FBA Inventory lets you programmatically retrieve information about inventory in Amazon's fulfillment network. Today this API is available only in the North America region. In 2021 we plan to release this API in the Europe and Far East regions.
*/
namespace DoubleBreak\Spapi\Api;
use DoubleBreak\Spapi\Client;

class FbaInventory extends Client {

  /**
  * Operation getInventorySummaries
  *
  * @param array $queryParams
  *    - *details* boolean - true to return inventory summaries with additional summarized inventory details and quantities. Otherwise, returns inventory summaries only (default value).
  *    - *granularityType* string - The granularity type for the inventory aggregation level.
  *    - *granularityId* string - The granularity ID for the inventory aggregation level.
  *    - *startDateTime* string - A start date and time in ISO8601 format. If specified, all inventory summaries that have changed since then are returned. You must specify a date and time that is no earlier than 18 months prior to the date and time when you call the API. Note: Changes in inboundWorkingQuantity, inboundShippedQuantity and inboundReceivingQuantity are not detected.
  *    - *sellerSkus* array - A list of seller SKUs for which to return inventory summaries. You may specify up to 50 SKUs.
  *    - *nextToken* string - String token returned in the response of your previous request.
  *    - *marketplaceIds* array - The marketplace ID for the marketplace for which to return inventory summaries.
  *
  */
  public function getInventorySummaries($queryParams = [])
  {
    return $this->send("/fba/inventory/v1/summaries", [
      'method' => 'GET',
      'query' => $queryParams,
    ]);
  }

  public function getInventorySummariesAsync($queryParams = [])
  {
    return $this->sendAsync("/fba/inventory/v1/summaries", [
      'method' => 'GET',
      'query' => $queryParams,
    ]);
  }
}
