<?php
/**
* This class is autogenerated by the Spapi class generator
* Date of generation: 2022-05-26
* Specification: https://github.com/amzn/selling-partner-api-models/blob/main/models/fulfillment-outbound-api-model/fulfillmentOutbound_2020-07-01.json
* Source MD5 signature: 3f57edb71b98d64ffe03e94fddeac0fe
*
*
* Selling Partner APIs for Fulfillment Outbound
* The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.
*/
namespace DoubleBreak\Spapi\Api;
use DoubleBreak\Spapi\Client;

class FulfillmentOutbound extends Client {

  /**
  * Operation getFulfillmentPreview
  *
  */
  public function getFulfillmentPreview($body = [])
  {
    return $this->send("/fba/outbound/2020-07-01/fulfillmentOrders/preview", [
      'method' => 'POST',
      'json' => $body
    ]);
  }

  public function getFulfillmentPreviewAsync($body = [])
  {
    return $this->sendAsync("/fba/outbound/2020-07-01/fulfillmentOrders/preview", [
      'method' => 'POST',
      'json' => $body
    ]);
  }

  /**
  * Operation listAllFulfillmentOrders
  *
  * @param array $queryParams
  *    - *queryStartDate* string - A date used to select fulfillment orders that were last updated after (or at) a specified time. An update is defined as any change in fulfillment order status, including the creation of a new fulfillment order.
  *    - *nextToken* string - A string token returned in the response to your previous request.
  *
  */
  public function listAllFulfillmentOrders($queryParams = [])
  {
    return $this->send("/fba/outbound/2020-07-01/fulfillmentOrders", [
      'method' => 'GET',
      'query' => $queryParams,
    ]);
  }

  public function listAllFulfillmentOrdersAsync($queryParams = [])
  {
    return $this->sendAsync("/fba/outbound/2020-07-01/fulfillmentOrders", [
      'method' => 'GET',
      'query' => $queryParams,
    ]);
  }

  /**
  * Operation createFulfillmentOrder
  *
  */
  public function createFulfillmentOrder($body = [])
  {
    return $this->send("/fba/outbound/2020-07-01/fulfillmentOrders", [
      'method' => 'POST',
      'json' => $body
    ]);
  }

  public function createFulfillmentOrderAsync($body = [])
  {
    return $this->sendAsync("/fba/outbound/2020-07-01/fulfillmentOrders", [
      'method' => 'POST',
      'json' => $body
    ]);
  }

  /**
  * Operation getPackageTrackingDetails
  *
  * @param array $queryParams
  *    - *packageNumber* integer - The unencrypted package identifier returned by the getFulfillmentOrder operation.
  *
  */
  public function getPackageTrackingDetails($queryParams = [])
  {
    return $this->send("/fba/outbound/2020-07-01/tracking", [
      'method' => 'GET',
      'query' => $queryParams,
    ]);
  }

  public function getPackageTrackingDetailsAsync($queryParams = [])
  {
    return $this->sendAsync("/fba/outbound/2020-07-01/tracking", [
      'method' => 'GET',
      'query' => $queryParams,
    ]);
  }

  /**
  * Operation listReturnReasonCodes
  *
  * @param array $queryParams
  *    - *sellerSku* string - The seller SKU for which return reason codes are required.
  *    - *marketplaceId* string - The marketplace for which the seller wants return reason codes.
  *    - *sellerFulfillmentOrderId* string - The identifier assigned to the item by the seller when the fulfillment order was created. The service uses this value to determine the marketplace for which the seller wants return reason codes.
  *    - *language* string - The language that the TranslatedDescription property of the ReasonCodeDetails response object should be translated into.
  *
  */
  public function listReturnReasonCodes($queryParams = [])
  {
    return $this->send("/fba/outbound/2020-07-01/returnReasonCodes", [
      'method' => 'GET',
      'query' => $queryParams,
    ]);
  }

  public function listReturnReasonCodesAsync($queryParams = [])
  {
    return $this->sendAsync("/fba/outbound/2020-07-01/returnReasonCodes", [
      'method' => 'GET',
      'query' => $queryParams,
    ]);
  }

  /**
  * Operation createFulfillmentReturn
  *
  * @param string $sellerFulfillmentOrderId An identifier assigned by the seller to the fulfillment order at the time it was created. The seller uses their own records to find the correct SellerFulfillmentOrderId value based on the buyer's request to return items.
  *
  */
  public function createFulfillmentReturn($sellerFulfillmentOrderId, $body = [])
  {
    return $this->send("/fba/outbound/2020-07-01/fulfillmentOrders/{$sellerFulfillmentOrderId}/return", [
      'method' => 'PUT',
      'json' => $body
    ]);
  }

  public function createFulfillmentReturnAsync($sellerFulfillmentOrderId, $body = [])
  {
    return $this->sendAsync("/fba/outbound/2020-07-01/fulfillmentOrders/{$sellerFulfillmentOrderId}/return", [
      'method' => 'PUT',
      'json' => $body
    ]);
  }

  /**
  * Operation getFulfillmentOrder
  *
  * @param string $sellerFulfillmentOrderId The identifier assigned to the item by the seller when the fulfillment order was created.
  *
  */
  public function getFulfillmentOrder($sellerFulfillmentOrderId)
  {
    return $this->send("/fba/outbound/2020-07-01/fulfillmentOrders/{$sellerFulfillmentOrderId}", [
      'method' => 'GET',
    ]);
  }

  public function getFulfillmentOrderAsync($sellerFulfillmentOrderId)
  {
    return $this->sendAsync("/fba/outbound/2020-07-01/fulfillmentOrders/{$sellerFulfillmentOrderId}", [
      'method' => 'GET',
    ]);
  }

  /**
  * Operation updateFulfillmentOrder
  *
  * @param string $sellerFulfillmentOrderId The identifier assigned to the item by the seller when the fulfillment order was created.
  *
  */
  public function updateFulfillmentOrder($sellerFulfillmentOrderId, $body = [])
  {
    return $this->send("/fba/outbound/2020-07-01/fulfillmentOrders/{$sellerFulfillmentOrderId}", [
      'method' => 'PUT',
      'json' => $body
    ]);
  }

  public function updateFulfillmentOrderAsync($sellerFulfillmentOrderId, $body = [])
  {
    return $this->sendAsync("/fba/outbound/2020-07-01/fulfillmentOrders/{$sellerFulfillmentOrderId}", [
      'method' => 'PUT',
      'json' => $body
    ]);
  }

  /**
  * Operation cancelFulfillmentOrder
  *
  * @param string $sellerFulfillmentOrderId The identifier assigned to the item by the seller when the fulfillment order was created.
  *
  */
  public function cancelFulfillmentOrder($sellerFulfillmentOrderId)
  {
    return $this->send("/fba/outbound/2020-07-01/fulfillmentOrders/{$sellerFulfillmentOrderId}/cancel", [
      'method' => 'PUT',
    ]);
  }

  public function cancelFulfillmentOrderAsync($sellerFulfillmentOrderId)
  {
    return $this->sendAsync("/fba/outbound/2020-07-01/fulfillmentOrders/{$sellerFulfillmentOrderId}/cancel", [
      'method' => 'PUT',
    ]);
  }

  /**
  * Operation getFeatures
  *
  * @param array $queryParams
  *    - *marketplaceId* string - The marketplace for which to return the list of features.
  *
  */
  public function getFeatures($queryParams = [])
  {
    return $this->send("/fba/outbound/2020-07-01/features", [
      'method' => 'GET',
      'query' => $queryParams,
    ]);
  }

  public function getFeaturesAsync($queryParams = [])
  {
    return $this->sendAsync("/fba/outbound/2020-07-01/features", [
      'method' => 'GET',
      'query' => $queryParams,
    ]);
  }

  /**
  * Operation getFeatureInventory
  *
  * @param string $featureName The name of the feature for which to return a list of eligible inventory.
  *
  * @param array $queryParams
  *    - *marketplaceId* string - The marketplace for which to return a list of the inventory that is eligible for the specified feature.
  *    - *nextToken* string - A string token returned in the response to your previous request that is used to return the next response page. A value of null will return the first page.
  *
  */
  public function getFeatureInventory($featureName, $queryParams = [])
  {
    return $this->send("/fba/outbound/2020-07-01/features/inventory/{$featureName}", [
      'method' => 'GET',
      'query' => $queryParams,
    ]);
  }

  public function getFeatureInventoryAsync($featureName, $queryParams = [])
  {
    return $this->sendAsync("/fba/outbound/2020-07-01/features/inventory/{$featureName}", [
      'method' => 'GET',
      'query' => $queryParams,
    ]);
  }

  /**
  * Operation getFeatureSKU
  *
  * @param string $featureName The name of the feature.
  * @param string $sellerSku Used to identify an item in the given marketplace. SellerSKU is qualified by the seller's SellerId, which is included with every operation that you submit.
  *
  * @param array $queryParams
  *    - *marketplaceId* string - The marketplace for which to return the count.
  *
  */
  public function getFeatureSKU($featureName, $sellerSku, $queryParams = [])
  {
    return $this->send("/fba/outbound/2020-07-01/features/inventory/{$featureName}/{$sellerSku}", [
      'method' => 'GET',
      'query' => $queryParams,
    ]);
  }

  public function getFeatureSKUAsync($featureName, $sellerSku, $queryParams = [])
  {
    return $this->sendAsync("/fba/outbound/2020-07-01/features/inventory/{$featureName}/{$sellerSku}", [
      'method' => 'GET',
      'query' => $queryParams,
    ]);
  }
}
