<?php
/**
* This class is autogenerated by the Spapi class generator
* Date of generation: 2022-05-26
* Specification: https://github.com/amzn/selling-partner-api-models/blob/main/models/sellers-api-model/sellers.json
* Source MD5 signature: c5098b08a5adb7f3c18ec07e5f39bb30
*
*
* Selling Partner API for Sellers
* The Selling Partner API for Sellers lets you retrieve information on behalf of sellers about their seller account, such as the marketplaces they participate in. Along with listing the marketplaces that a seller can sell in, the API also provides additional information about the marketplace such as the default language and the default currency. The API also provides seller-specific information such as whether the seller has suspended listings in that marketplace.
*/
namespace DoubleBreak\Spapi\Api;
use DoubleBreak\Spapi\Client;

class Sellers extends Client {

  /**
  * Operation getMarketplaceParticipations
  *
  */
  public function getMarketplaceParticipations()
  {
    return $this->send("/sellers/v1/marketplaceParticipations", [
      'method' => 'GET',
    ]);
  }

  public function getMarketplaceParticipationsAsync()
  {
    return $this->sendAsync("/sellers/v1/marketplaceParticipations", [
      'method' => 'GET',
    ]);
  }
}
