<?php
/**
* This class is autogenerated by the Spapi class generator
* Date of generation: 2022-01-09
* Specification: https://github.com/amzn/selling-partner-api-models/blob/main/models/shipment-invoicing-api-model/shipmentInvoicingV0.json
* Source MD5 signature: 7d20e570a133b181b46ab385d9790b63
*
*
* Selling Partner API for Shipment Invoicing
* The Selling Partner API for Shipment Invoicing helps you programmatically retrieve shipment invoice information in the Brazil marketplace for a selling partner’s Fulfillment by Amazon (FBA) orders.
*/
namespace DoubleBreak\Spapi\Api;
use DoubleBreak\Spapi\Client;

class ShipmentInvoicing extends Client {

  /**
  * Operation getShipmentDetails
  *
  * @param string $shipmentId The identifier for the shipment. Get this value from the FBAOutboundShipmentStatus notification. For information about subscribing to notifications, see the [Notifications API Use Case Guide](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/notifications-api-use-case-guide/notifications-use-case-guide-v1.md).
  *
  */
  public function getShipmentDetails($shipmentId)
  {
    return $this->send("/fba/outbound/brazil/v0/shipments/{$shipmentId}", [
      'method' => 'GET',
    ]);
  }

  public function getShipmentDetailsAsync($shipmentId)
  {
    return $this->sendAsync("/fba/outbound/brazil/v0/shipments/{$shipmentId}", [
      'method' => 'GET',
    ]);
  }

  /**
  * Operation submitInvoice
  *
  * @param string $shipmentId The identifier for the shipment.
  *
  */
  public function submitInvoice($shipmentId, $body = [])
  {
    return $this->send("/fba/outbound/brazil/v0/shipments/{$shipmentId}/invoice", [
      'method' => 'POST',
      'json' => $body
    ]);
  }

  public function submitInvoiceAsync($shipmentId, $body = [])
  {
    return $this->sendAsync("/fba/outbound/brazil/v0/shipments/{$shipmentId}/invoice", [
      'method' => 'POST',
      'json' => $body
    ]);
  }

  /**
  * Operation getInvoiceStatus
  *
  * @param string $shipmentId The shipment identifier for the shipment.
  *
  */
  public function getInvoiceStatus($shipmentId)
  {
    return $this->send("/fba/outbound/brazil/v0/shipments/{$shipmentId}/invoice/status", [
      'method' => 'GET',
    ]);
  }

  public function getInvoiceStatusAsync($shipmentId)
  {
    return $this->sendAsync("/fba/outbound/brazil/v0/shipments/{$shipmentId}/invoice/status", [
      'method' => 'GET',
    ]);
  }
}
