<?php
/**
* This class is autogenerated by the Spapi class generator
* Date of generation: 2022-01-09
* Specification: https://github.com/amzn/selling-partner-api-models/blob/main/models/shipping-api-model/shipping.json
* Source MD5 signature: 675872eacd6e241145f5d787b4806133
*
*
* Selling Partner API for Shipping
* Provides programmatic access to Amazon Shipping APIs.
*/
namespace DoubleBreak\Spapi\Api;
use DoubleBreak\Spapi\Client;

class Shipping extends Client {

  /**
  * Operation createShipment
  *
  */
  public function createShipment($body = [])
  {
    return $this->send("/shipping/v1/shipments", [
      'method' => 'POST',
      'json' => $body
    ]);
  }

  public function createShipmentAsync($body = [])
  {
    return $this->sendAsync("/shipping/v1/shipments", [
      'method' => 'POST',
      'json' => $body
    ]);
  }

  /**
  * Operation getShipment
  *
  * @param string $shipmentId 
  *
  */
  public function getShipment($shipmentId)
  {
    return $this->send("/shipping/v1/shipments/{$shipmentId}", [
      'method' => 'GET',
    ]);
  }

  public function getShipmentAsync($shipmentId)
  {
    return $this->sendAsync("/shipping/v1/shipments/{$shipmentId}", [
      'method' => 'GET',
    ]);
  }

  /**
  * Operation cancelShipment
  *
  * @param string $shipmentId 
  *
  */
  public function cancelShipment($shipmentId)
  {
    return $this->send("/shipping/v1/shipments/{$shipmentId}/cancel", [
      'method' => 'POST',
    ]);
  }

  public function cancelShipmentAsync($shipmentId)
  {
    return $this->sendAsync("/shipping/v1/shipments/{$shipmentId}/cancel", [
      'method' => 'POST',
    ]);
  }

  /**
  * Operation purchaseLabels
  *
  * @param string $shipmentId 
  *
  */
  public function purchaseLabels($shipmentId, $body = [])
  {
    return $this->send("/shipping/v1/shipments/{$shipmentId}/purchaseLabels", [
      'method' => 'POST',
      'json' => $body
    ]);
  }

  public function purchaseLabelsAsync($shipmentId, $body = [])
  {
    return $this->sendAsync("/shipping/v1/shipments/{$shipmentId}/purchaseLabels", [
      'method' => 'POST',
      'json' => $body
    ]);
  }

  /**
  * Operation retrieveShippingLabel
  *
  * @param string $shipmentId 
  * @param string $trackingId 
  *
  */
  public function retrieveShippingLabel($shipmentId, $trackingId, $body = [])
  {
    return $this->send("/shipping/v1/shipments/{$shipmentId}/containers/{$trackingId}/label", [
      'method' => 'POST',
      'json' => $body
    ]);
  }

  public function retrieveShippingLabelAsync($shipmentId, $trackingId, $body = [])
  {
    return $this->sendAsync("/shipping/v1/shipments/{$shipmentId}/containers/{$trackingId}/label", [
      'method' => 'POST',
      'json' => $body
    ]);
  }

  /**
  * Operation purchaseShipment
  *
  */
  public function purchaseShipment($body = [])
  {
    return $this->send("/shipping/v1/purchaseShipment", [
      'method' => 'POST',
      'json' => $body
    ]);
  }

  public function purchaseShipmentAsync($body = [])
  {
    return $this->sendAsync("/shipping/v1/purchaseShipment", [
      'method' => 'POST',
      'json' => $body
    ]);
  }

  /**
  * Operation getRates
  *
  */
  public function getRates($body = [])
  {
    return $this->send("/shipping/v1/rates", [
      'method' => 'POST',
      'json' => $body
    ]);
  }

  public function getRatesAsync($body = [])
  {
    return $this->sendAsync("/shipping/v1/rates", [
      'method' => 'POST',
      'json' => $body
    ]);
  }

  /**
  * Operation getAccount
  *
  */
  public function getAccount()
  {
    return $this->send("/shipping/v1/account", [
      'method' => 'GET',
    ]);
  }

  public function getAccountAsync()
  {
    return $this->sendAsync("/shipping/v1/account", [
      'method' => 'GET',
    ]);
  }

  /**
  * Operation getTrackingInformation
  *
  * @param string $trackingId 
  *
  */
  public function getTrackingInformation($trackingId)
  {
    return $this->send("/shipping/v1/tracking/{$trackingId}", [
      'method' => 'GET',
    ]);
  }

  public function getTrackingInformationAsync($trackingId)
  {
    return $this->sendAsync("/shipping/v1/tracking/{$trackingId}", [
      'method' => 'GET',
    ]);
  }
}
