<?php
/**
* This class is autogenerated by the Spapi class generator
* Date of generation: 2021-06-06
* Specification: ttps://github.com/amzn/selling-partner-api-models/blob/main/models/tokens-api-model/tokens.json
* Source MD5 signature: 7baeb2a3d9039a58b364106efd6c3879
*
*
* Selling Partner API for Tokens
* The Selling Partner API for Tokens provides a secure way to access a customers's PII (Personally Identifiable Information). You can call the Tokens API to get a Restricted Data Token (RDT) for one or more restricted resources that you specify. The RDT authorizes you to make subsequent requests to access these restricted resources.
*/
namespace DoubleBreak\Spapi\Api;
use DoubleBreak\Spapi\Client;


class Tokens extends Client {

  /**
  * Operation createRestrictedDataToken
  *
  */
  public function createRestrictedDataToken($body = [])
  {
    return $this->send("/tokens/2021-03-01/restrictedDataToken", [
      'method' => 'POST',
      'json' => $body
    ]);
  }
}
