<?php
/**
* This class is autogenerated by the Spapi class generator
* Date of generation: 2022-05-26
* Specification: https://github.com/amzn/selling-partner-api-models/blob/main/models/vendor-invoices-api-model/vendorInvoices.json
* Source MD5 signature: 971d3f0d56ddb378d5eddbc92da6337b
*
*
* Selling Partner API for Retail Procurement Payments
* The Selling Partner API for Retail Procurement Payments provides programmatic access to vendors payments data.
*/
namespace DoubleBreak\Spapi\Api;
use DoubleBreak\Spapi\Client;

class VendorInvoices extends Client {

  /**
  * Operation submitInvoices
  *
  */
  public function submitInvoices($body = [])
  {
    return $this->send("/vendor/payments/v1/invoices", [
      'method' => 'POST',
      'json' => $body
    ]);
  }

  public function submitInvoicesAsync($body = [])
  {
    return $this->sendAsync("/vendor/payments/v1/invoices", [
      'method' => 'POST',
      'json' => $body
    ]);
  }
}
