<?php
/**
* This class is autogenerated by the Spapi class generator
* Date of generation: 2022-01-09
* Specification: https://github.com/amzn/selling-partner-api-models/blob/main/models/vendor-direct-fulfillment-inventory-api-model/vendorDirectFulfillmentInventoryV1.json
* Source MD5 signature: 0eeaabd42dddbe5e2cb0fd433abd9b61
*
*
* Selling Partner API for Direct Fulfillment Inventory Updates
* The Selling Partner API for Direct Fulfillment Inventory Updates provides programmatic access to a direct fulfillment vendor's inventory updates.
*/
namespace DoubleBreak\Spapi\Api;
use DoubleBreak\Spapi\Client;

class VendorDirectFulfillmentInventory extends Client {

  /**
  * Operation submitInventoryUpdate
  *
  * @param string $warehouseId Identifier for the warehouse for which to update inventory.
  *
  */
  public function submitInventoryUpdate($warehouseId, $body = [])
  {
    return $this->send("/vendor/directFulfillment/inventory/v1/warehouses/{$warehouseId}/items", [
      'method' => 'POST',
      'json' => $body
    ]);
  }

  public function submitInventoryUpdateAsync($warehouseId, $body = [])
  {
    return $this->sendAsync("/vendor/directFulfillment/inventory/v1/warehouses/{$warehouseId}/items", [
      'method' => 'POST',
      'json' => $body
    ]);
  }
}
