<?php
/**
* This class is autogenerated by the Spapi class generator
* Date of generation: 2022-05-26
* Specification: https://github.com/amzn/selling-partner-api-models/blob/main/models/vendor-shipments-api-model/vendorShipments.json
* Source MD5 signature: 83ee839f52203ffb14dc8bcf2418ace4
*
*
* Selling Partner API for Retail Procurement Shipments
* The Selling Partner API for Retail Procurement Shipments provides programmatic access to retail shipping data for vendors.
*/
namespace DoubleBreak\Spapi\Api;
use DoubleBreak\Spapi\Client;

class VendorShipments extends Client {

  /**
  * Operation SubmitShipmentConfirmations
  *
  */
  public function SubmitShipmentConfirmations($body = [])
  {
    return $this->send("/vendor/shipping/v1/shipmentConfirmations", [
      'method' => 'POST',
      'json' => $body
    ]);
  }

  public function SubmitShipmentConfirmationsAsync($body = [])
  {
    return $this->sendAsync("/vendor/shipping/v1/shipmentConfirmations", [
      'method' => 'POST',
      'json' => $body
    ]);
  }
}
