<?php
/**
* This class is autogenerated by the Spapi class generator
* Date of generation: 2022-01-09
* Specification: https://github.com/amzn/selling-partner-api-models/blob/main/models/vendor-direct-fulfillment-payments-api-model/vendorDirectFulfillmentPaymentsV1.json
* Source MD5 signature: caaa6efff5745d0817ad22735bc92bc5
*
*
* Selling Partner API for Direct Fulfillment Payments
* The Selling Partner API for Direct Fulfillment Payments provides programmatic access to a direct fulfillment vendor's invoice data.
*/
namespace DoubleBreak\Spapi\Api;
use DoubleBreak\Spapi\Client;

class VendorDirectFulfillmentPayments extends Client {

  /**
  * Operation submitInvoice
  *
  */
  public function submitInvoice($body = [])
  {
    return $this->send("/vendor/directFulfillment/payments/v1/invoices", [
      'method' => 'POST',
      'json' => $body
    ]);
  }

  public function submitInvoiceAsync($body = [])
  {
    return $this->sendAsync("/vendor/directFulfillment/payments/v1/invoices", [
      'method' => 'POST',
      'json' => $body
    ]);
  }
}
