<?php
/**
* This class is autogenerated by the Spapi class generator
* Date of generation: 2022-01-09
* Specification: https://github.com/amzn/selling-partner-api-models/blob/main/models/vendor-direct-fulfillment-transactions-api-model/vendorDirectFulfillmentTransactionsV1.json
* Source MD5 signature: 2aa36399c8462d2cae8ad5f3d2b7767c
*
*
* Selling Partner API for Direct Fulfillment Transaction Status
* The Selling Partner API for Direct Fulfillment Transaction Status provides programmatic access to a direct fulfillment vendor's transaction status.
*/
namespace DoubleBreak\Spapi\Api;
use DoubleBreak\Spapi\Client;

class VendorDirectFulfillmentTransactions extends Client {

  /**
  * Operation getTransactionStatus
  *
  * @param string $transactionId Previously returned in the response to the POST request of a specific transaction.
  *
  */
  public function getTransactionStatus($transactionId)
  {
    return $this->send("/vendor/directFulfillment/transactions/v1/transactions/{$transactionId}", [
      'method' => 'GET',
    ]);
  }

  public function getTransactionStatusAsync($transactionId)
  {
    return $this->sendAsync("/vendor/directFulfillment/transactions/v1/transactions/{$transactionId}", [
      'method' => 'GET',
    ]);
  }
}
